// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    Footer: typeof import('./components/Footer.vue')['default']
    MineBlock: typeof import('./components/MineBlock.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
